### ISSUE TITLE
Need automated update mechanism

### ISSUE THREAD

**Issue by archisman-panigrahi** [flathub/io.github.slgobinath.SafeEyes#15]
Will it be possible to add an automated update mechanism as soon as a new release is made, perhaps using GitHub actions?

BTW, a new version was released today.

**Comment by otuva** [comment]
Yeah, it can be automated, I was actually working on that sometime back using pypi. Gonna take a look at this again

**Comment by otuva** [comment]
After merging #16, will wait one upstream version bump to validate everything is ok

then I will enable the bot to merge version PRs  

at that point everything should be automatic

**Comment by archisman-panigrahi** [comment]
> will wait one upstream version bump

Incidentally, I just released 2.2.1

**Comment by otuva** [comment]
> Incidentally, I just released 2.2.1

Ok, after bot opens PR for the new version, I will test and enable the auto merge

**Comment by otuva** [comment]
Apparently flatpak team changed the option for the bot, and now it requires exception 

https://github.com/flathub-infra/flatpak-external-data-checker?tab=readme-ov-file#automatically-merging-prs

https://docs.flathub.org/blog/linter-restricting-automatic-merge/

At least bot opened PR quickly #17 

Even though updates are now automatic, it still requires manual testing and merging for now

**Comment by archisman-panigrahi** [comment]
Great!
